### ISSUE TITLE
Addition of timestamps

### ISSUE THREAD

**Issue by leonardodanelutti** [maxmindlin/telegraf-rust#10]
Can a way to specify a timestamp when a new point is created be implemented?

**Comment by maxmindlin** [comment]
Possibly, I've personally always allowed telegraf to add the timestamp, which I think is the most common use case. I'd have to look into and test adding timestamps to the telegraf input to make sure it works. I'll add this as a nice to have if I ever have time.

**Comment by leonardodanelutti** [comment]
Added timestamps in this pull request: #11

**Comment by maxmindlin** [comment]
Thanks so much for putting the work into writing up an implementation for this. Before I dive into the details of the PR can you explain your use case for timestamps? 

My hesitancy to adding them is that 
a.) Telegraf handles this well by default, adding timestamps if they are not present.
b.) My initial thought was that adding timestamps to the library adds/welcomes complications. Time is complicated and I worry it welcomes people to ask for additions to this topic which could be much more complicated. (Ex., we could provide no checks around user-provided timestamps and allow Telegraf itself to handle malformation vs. handling malformation ourselves. Decent arguments to both sides IMO).

Thanks again for taking time on this!

**Comment by leonardodanelutti** [comment]
Thank you for sharing your opinion! 

In my specific case i need to add the timestamps because the data i receive in my application has a field with a timestamp, these could be unordered and significant time could have passed since the data was created.

I have not removed the possibility that telegraf manages them by themselves, in fact the additions are all backwards compatible with previous versions. probably the use case without the timestamp specification is the most frequent one but I think their addition is necessary for some use cases.

For now the timestamp field is always cast to an unsigned integer, right now I can't think of any other checks to perform.

Let me know what you think!

**Comment by maxmindlin** [comment]
> In my specific case i need to add the timestamps because the data i receive in my application has a field with a timestamp, these could be unordered and significant time could have passed since the data was created.

I hadn't considered this! Thanks for the write-up. I think timestamps are worth considering adding then as long as significant complexity isn't inherited with it.

I'll take a look through the PR when I get a moment and leave review there. Thanks!

**Comment by leonardodanelutti** [comment]
Sure, thank you for considering the addition of timestamps!

**Comment by leonardodanelutti** [comment]
Will this feature be released?

**Comment by maxmindlin** [comment]
Yes I will release a new minor version this week. I like to give the repo a look over before releasing minor & major versions.
