### ISSUE TITLE
write point fails with `broken pipe (os error 32)`

### ISSUE THREAD

**Issue by rabarar** [maxmindlin/telegraf-rust#14]
### Subject of the issue
Describe your issue here.

after some amount of time, a write fails with the OS 32 error mentioned above

### Your environment
* version of Telegraf-rust
0.6.0

* version of Rust
1.68.2  (9eb3afe9e 2023-03-27)

### Steps to reproduce
Tell us how to reproduce this issue.

write a bunch of points in a loop for a few hours! :)  (check out my public repo... github.com/rabarar/homie-telegraf

### Expected behaviour
Tell us what should happen
should be able to drop the connection and reconnect and continue writing...

### Actual behaviour
Tell us what happens instead
seems to not recover unless the process is terminated and restarted

**Comment by maxmindlin** [comment]
Hello! 

From my understanding this fails when the tcp server fails, which would be in this case the telegraf daemon. Have you tried closing and re-instantiating the client in the case this error is thrown?

**Comment by rabarar** [comment]
What I’ve tried that seems to be working is dropping and then reconnecting… without dropping it says it’s reconnected, yet the error writing persists. I’m running it now and will see if dropping the connection resolves the issueOn Apr 17, 2023, at 11:04 AM, maxmindlin ***@***.***> wrote:﻿
Hello!
From my understanding this fails when the tcp server fails, which would be in this case the telegraf daemon. Have you tried closing and re-instantiating the client in the case this error is thrown?

**Comment by maxmindlin** [comment]
Are there any logs from the telegraf daemon that might suggest an issue there?

I'm not sure I like the idea of changing the client to automatically reconnect. However, a compromise I think might be worth exploring would be surfacing a method that would close and reconnect the internal socket connection so you wouldnt have to re-instantiate the entire client.

**Comment by rabarar** [comment]
Surprisingly, no error messages from telegraf… On Apr 17, 2023, at 11:19 AM, maxmindlin ***@***.***> wrote:﻿
Are there any logs from the telegraf daemon that might suggest an issue there?
I'm not sure I like the idea of changing the client to automatically reconnect. However, a compromise I think might be worth exploring would be surfacing a method that would close and reconnect the internal socket connection so you wouldnt have to re-instantiate the entire client.

**Comment by rabarar** [comment]
So it seems to happen and i see no log info from Telegraf ... At this point, I'll panic so Docker can restart the app... unless you see something that I'm not, I don't see why it's failing without logging if it was an issue on the server side

**Comment by maxmindlin** [comment]
Well Im in a tough spot because this is something I havent been able to reproduce (I dont have access to linux machine currently) and is not obviously something wrong with the code thats easy to dive into. Im happy to accept PRs or look into it further if someone else also has this issue.

If you can confirm that restarted the socket connector/client in-code solves the issue, then I might be willing to dive into surfacing a method to close and re-open the socket connector manually (`Client::reconnect` or something).

**Comment by rabarar** [comment]
Completely understand… let me see if I can add some debugging to isolate it… hold tight and let me see if I can zoom in…On Apr 20, 2023, at 5:27 PM, maxmindlin ***@***.***> wrote:﻿
Well Im in a tough spot because this is something I havent been able to reproduce (I dont have access to linux machine currently) and is not obviously something wrong with the code thats easy to dive into. Im happy to accept PRs or look into it further if someone else also has this issue.
If you can confirm that restarted the socket connector/client in-code solves the issue, then I might be willing to dive into surfacing a method to close and re-open the socket connector manually (Client::reconnect or something).

**Comment by maxmindlin** [comment]
Thanks!

**Comment by rabarar** [comment]
first thing I’m going to do is switch to udp from tcp and isolate the transport from the code
