### ISSUE TITLE
Allow for optional `Metric` fields

### ISSUE THREAD

**Issue by djahandarie** [maxmindlin/telegraf-rust#2]
Since InfluxDB's line protocol doesn't allow for explicitly specifying a null value, the only way to accomplish it is by not providing the field.

Currently `Metric` doesn't let you make one of the fields an `Option`, so I don't believe there's a way to accomplish this with the library currently.

**Comment by maxmindlin** [comment]
Sorry for the late response - nice find! I believe you could achieve this by using the `point!` macro or explicit `Point::new` method instead of the `Metric` procedural macro. Obviously this isn't ideal since `Metric` is nicer to use so I will look into adding that functionality to that macro!
