### ISSUE TITLE
Implementation of more primitive types for trait IntoFieldData.

### ISSUE THREAD

**Issue by leonardodanelutti** [maxmindlin/telegraf-rust#6]
Implementation of primitive types for a trait from outside a create is impossible, I need the implementation of IntoFieldData for u16, i16 and i8 and I can't find a way to do so. Is it possible to add more primitive types, in particular i16, i8, u16 and u8.

**Comment by maxmindlin** [comment]
Thanks for the issue! Easy enough, I can add these.
